### ISSUE TITLE
Create Partner Dialog

### ISSUE THREAD

**Issue by cedrickf** [fom-pm-se/frontend#42]
### Userstory
Als MA möchte ich einen neuen Partner über einen Dialog anlegen können, damit ich Partner leicht pflegen kann.

### Akzeptanzkriterien
- [x] Dialog ist über eine Schaltfläche in der Partnerliste erreichbar
- [x] Folgende Attribute können gepflegt werden: Name, Adresse, Telefonnummer, Typ (Kunde, Zuliferer, sonstiger Geschäftspartner)

**Comment by leonschbbht** [comment]
Was ist denn unser fachlicher Primärschlüssel für Partner? Der Name? Oder eine Kombination aus Name und Adresse?

**Comment by cedrickf** [comment]
Entweder eine ID oder der Name. Der Name müsste dann mit Unternehmensform geführt sein.
