### ISSUE TITLE
Partnerliste

### ISSUE THREAD

**Issue by cedrickf** [fom-pm-se/frontend#43]
### Userstory
Als MA möchte ich eine Schaltfläche haben (linker Rand) über die ich eine Liste aller Partner bekomme.

### Akzeptanzkriterien

- [x] Liste ist für angemeldete Benutzer über Sidebar aufrufbar
- [x] Die Liste enthält alle Partner inklusive ihres Profilbilds, des Namens und des Typs
- [x] Klickt man einen partner an öffnet sich ein modaler Dialog mit den Details (#45)
- [x] Audit Informationen werden in den Details angezeigt (Angelegt am, Angelegt von, Geändert am, Geändert von) (#45)

**Comment by leonschbbht** [comment]
Ich habe die Abnahmebedingungen ergänzt. Passt das?

**Comment by cedrickf** [comment]
Passt
