### ISSUE TITLE
Filterung Partnerliste

### ISSUE THREAD

**Issue by cedrickf** [fom-pm-se/frontend#44]
### Userstory
Als MA möchte ich in der Partnerliste über Filter die dargestellten Partner sortieren und filtern können, um schneller den richtigen Partner zu finden

### Akzeptanzkriterien

- [x] Filtermenü über der Partnerliste hinzugefügt
- [x] Partner können nach "Namen" gefiltert werden
- [x] Partner können nach Typ (Kunde, Zulieferer, sonstiger Geschäftspartner) gefiltert werden
- [x] Partner können nach Name, Typ, Erstellungsdatum und Änderungsdatum sortiert werden

**Comment by leonschbbht** [comment]
Ich habe die Abnahmebedingungen hinzugefügt. Schau mal drüber ob das für dich passt

**Comment by cedrickf** [comment]
Das passt.
