### ISSUE TITLE
Kalender/ Telefontermin Funktion

### ISSUE THREAD

**Issue by cedrickf** [fom-pm-se/frontend#52]
### Userstory

Als User/Key Accounter/ Sekretariat möchte ich Telefontermine anlegen können damit ich eine Integration zwischen CRM und Outlook Kalender erreichen kann.

### Akzeptanzkriterien / Abnahmevoraussetzungen

- [x] Auf der Partnerdetailseite ist ein Button zur Terminanlage vorhanden.
- [ ] Termine können mit Uhrzeit, Datum und Notiz angelegt werden.
- [x] Es wird eine iCal Datei erstellt.
- [ ] Termine werden farblich abgehoben im Kommunikationsverlauf auf der Partnerdetailseite angezeigt.

**Comment by leonschbbht** [comment]
Frontend ist @ArthurHardCoding  Anwendungsbereich, deswegen habe ich mich mal als Bearbeiter entfernt :)
